openapi: 3.0.0
info:
  title: OpenAPI спецификация каталога детских игрушек
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server  
  
paths:
  /docs:
    get:
      summary: Метод получения шаблонов
      description: Метод предназначен для получения списка всех шаблонов, сохраненных в БД.
      operationId: getDocs
      tags:
        - Doc
      responses:
        '200':
          "description": Список шаблонов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Templates"
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод добавления нового шаблона в каталог
      description: Метод предназначен для сохранения в БД данных по нового шаблона.
      operationId: createTemplate
      tags:
        - Doc
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/Template"
      responses:
        '200':
          "description": Подтверждение успешного сохранения
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        '400':
          "description": Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /docs/{id}:
    get:
      summary: Метод получения шаблона по идентификатору
      operationId: getTemplateById
      tags:
        - Doc
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор шаблона
          schema:
            type: string
      responses:
        '200':
          "description": Шаблон
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Метод обновления шаблона и в каталоге
      description: Метод предназначен для обновления в БД данных по имеющейся шаблона.
      operationId: updateTemplate
      tags:
        - Doc
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор шаблона
          schema:
            type: string
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/Template"
      responses:
        '200':
          "description": Подтверждение успешного обновления
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        '400':
          "description": Некорректные входные данные. Возвращает список атрибутов с ошибками
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Метод удаления шаблона по идентификатору
      operationId: deleteTemplatyById
      tags:
        - Doc
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор игрушки
          schema:
            type: string
      responses:
        '200':
          "description": Успешное удаление
          content:
            'application/json': {}
        default:
          description: Любая неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

                
components:
  schemas:
    Template:
      type: object
      required:
        - name
        - owner
      properties:
        id:
          type: string
          example: 1
        name:
          description: Название шаблона
          type: string
          example: Дкп квартиры
        owner:
          description: владелец
          type: string
          example: new
        template:
          description: Путь к шаблону
          type: string
          example: Found on a street
        category_id:
          description: категория шаблона
          type: string
          example: Юр лицо
        modifed:
          type: string
          example: 23.09.2023
        deleted:
          type: boolean
          example: True
          
    Templates:
      type: array
      items:
        $ref: "#/components/schemas/Template"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string