# Generated by Django 3.2 on 2024-01-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование обьекта')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(verbose_name='Удален')),
                ('description', models.TextField(verbose_name='Описание обьета')),
            ],
            options={
                'verbose_name': 'Обьект',
                'verbose_name_plural': 'Обьекты',
                'ordering': ('name',),
                'default_related_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ObjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование поля')),
                ('default', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение по умолчанию')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='base_objects.object', verbose_name='Обьект')),
            ],
            options={
                'verbose_name': 'Поле обьекта',
                'verbose_name_plural': 'Поля обьекта',
                'ordering': ('object', 'name'),
                'default_related_name': 'fields',
            },
        ),
    ]
