# Generated by Django 3.2 on 2024-01-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='base_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_objects', to='base_objects.baseobject', verbose_name='поля базового Обьект'),
        ),
    ]
