# Generated by Django 3.2 on 2024-01-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование шаблона обьекта')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(verbose_name='Удален')),
                ('description', models.TextField(verbose_name='Описание базового обьекта')),
            ],
            options={
                'verbose_name': 'Шаблон Обьект',
                'verbose_name_plural': 'Шаблон Обьекты',
                'ordering': ('name',),
                'default_related_name': 'Base_objects',
            },
        ),
        migrations.AlterModelOptions(
            name='object',
            options={},
        ),
        migrations.AlterModelOptions(
            name='objectfield',
            options={'verbose_name': 'Поле обьекта', 'verbose_name_plural': 'Поля обьекта'},
        ),
        migrations.RemoveField(
            model_name='object',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='object',
            name='description',
        ),
        migrations.RemoveField(
            model_name='object',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='objectfield',
            name='default',
        ),
        migrations.RemoveField(
            model_name='objectfield',
            name='name',
        ),
        migrations.AddField(
            model_name='objectfield',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Содержимое поля'),
        ),
        migrations.AlterField(
            model_name='objectfield',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_objects.object', verbose_name='Обьект'),
        ),
        migrations.CreateModel(
            name='BaseObjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование базового поля обьекта')),
                ('default', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение по умолчанию')),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_fields', to='base_objects.baseobject', verbose_name='поля базового Обьект')),
            ],
            options={
                'verbose_name': 'Поле базового обьекта',
                'verbose_name_plural': 'Поля базового обьекта',
                'default_related_name': 'base_fields',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='base_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_objects.baseobject', verbose_name='Обьект'),
        ),
        migrations.AddField(
            model_name='objectfield',
            name='base_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_fields', to='base_objects.baseobjectfield', verbose_name='Поле'),
        ),
    ]
