# Generated by Django 3.2 on 2024-01-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0002_auto_20240102_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'default_related_name': 'objects', 'verbose_name': 'Обьект', 'verbose_name_plural': 'Обьекты'},
        ),
        migrations.AddField(
            model_name='object',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='object',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='object',
            name='base_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='base_objects.baseobject', verbose_name='Обьект'),
        ),
    ]
