# Generated by Django 3.2 on 2024-01-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0003_auto_20240102_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseobject',
            options={'default_related_name': 'Base_objects', 'ordering': ('name',), 'verbose_name': 'базовый Обьекта', 'verbose_name_plural': 'базовые Обьекты'},
        ),
        migrations.RemoveField(
            model_name='baseobjectfield',
            name='default',
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование базового обьекта'),
        ),
    ]
