# Generated by Django 3.2 on 2024-01-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0004_auto_20240102_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='base_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='base_objects.baseobject', verbose_name='Юр или физ лицо'),
        ),
    ]
