# Generated by Django 3.2 on 2024-01-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0005_alter_object_base_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='base_object',
        ),
    ]
