@TOKEN = Token 77435c1657026635eda41cb962fb9d39d4054e17

###
GET http://127.0.0.1:8000/api/documents/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
POST http://127.0.0.1:8000/api/documents/
Content-Type: application/json
Authorization: {{TOKEN}}

{
      "id": 1,
      "created": "2023-10-09T09:28:40.010461Z",
      "completed": true,
      "description": "doc1",
      "template": 1,
      "owner": 1,
      "document_fields": [
        {
          "value": "123",
          "field": 2
        },
        {
          "value": "name field",
          "field": 1
        }
      ]
}

###
PATCH  http://127.0.0.1:8000/api/documents/1/
Content-Type: application/json
Authorization: {{TOKEN}}

{
      "id": 1,
      "created": "2023-10-09T09:28:40.010461Z",
      "completed": false,
      "description": "doc1z111",
      "template": 1,
      "owner": 1,
      "document_fields": [
        {
          "value": "114423",
          "field": 2
        },
        {
          "value": "114423",
          "field": 1
        }
      ]
}

###
get  http://127.0.0.1:8000/api/documents/draft/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
get  http://127.0.0.1:8000/api/documents/history/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}
