@TOKEN = Token bb4f5dbedaafd2730f35803e7087e797479d68f5
@URL = https://documents-template.site/

###
GET {{URL}}/api/documents/32/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
POST {{URL}}/api/documents/
Content-Type: application/json
Authorization: {{TOKEN}}

{
      "description": "doc1",
      "template": 1,
      "completed": true,
      "document_fields": [
        {
          "value": "66",
          "field": 1
        },
        {
          "value": "Непоседы",
          "field": 2
        },
        {
          "value": "Ивановой Ирине Петровне",
          "field": 3
        },
        {
          "value": "Иванова Ивана Ивановича",
          "field": 4
        },
        {
          "value": "город, улица, номер квартиры",
          "field": 5
        },
        {
          "value": "Сидоровым Данилой Игоревичем",
          "field": 6
        },
        {
          "value": "№3",
          "field": 7
        },
        {
          "value": "01.11.2023",
          "field": 8
        },
        {
          "value": "20.11.2023",
          "field": 9
        },
        {
          "value": "30.10.2023",
          "field": 10
        }
      ]
}

###
PATCH  {{URL}}/api/documents/2/
Content-Type: application/json
Authorization: {{TOKEN}}

{
      "id": 1,
      "created": "2023-10-09T09:28:40.010461Z",
      "completed": false,
      "description": "doc1z111",
      "template": 1,
      "owner": 1,
      "document_fields": [
        {
          "value": "66 Непоседы",
          "field": 1
        },
        {
          "value": "Ивановой Ирине Петровне",
          "field": 2
        },
        {
          "value": "Сидорова Петра Ивановича",
          "field": 3
        },
        {
          "value": "Москва, ул. Центральная, дом 11, кв. 323",
          "field": 4
        },
        {
          "value": "Сидоровым Данилой Петровичем",
          "field": 5
        },
        {
          "value": "№3",
          "field": 6
        },
        {
          "value": "1.11.2023",
          "field": 7
        },
        {
          "value": "20.11.2023",
          "field": 8
        },
        {
          "value": "30.10.2023",
          "field": 9
        }
      ]
}

###
get  {{URL}}/api/documents/draft/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
get  {{URL}}/api/documents/history/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

###
get  {{URL}}/api/documents/2/download_document/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

