@TOKEN = Token 66ba19730c8aaad7378dc20fae75656b06b00e02

@URL = https://doky.pro/api/v2
# @URL = http://localhost:8000/api/v2


### Все шаблоны
GET {{URL}}/templates/ 
Content-Type: application/json
# Authorization: {{TOKEN}}

{
}

### Просмотр одного шаблона
GET {{URL}}/templates/22/ 
Content-Type: application/json
Authorization: {{TOKEN}}

{
}


### Просмотр всех полей шаблона
GET {{URL}}/templates/42/fields
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

### Добавить шаблон в избранное
POST {{URL}}/templates/22/favorite/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

### Удалить шаблон из избранного
DELETE {{URL}}/templates/1/favorite/
Content-Type: application/json
Authorization: {{TOKEN}}

{
}


### Получить первью документа от анонимного пользователя
POST {{URL}}/templates/22/download_preview/
Content-Type: application/json
# Authorization: {{TOKEN}}

{
    "document_fields": [
        {
          "value": "66 Непоседы",
          "field": 1
        },
        {
          "value": "Ивановой Ирине Петровне",
          "field": 2
        },
        {
          "value": "Сидорова Петра Ивановича",
          "field": 3
        },
        {
          "value": "Москва, ул. Центральная, дом 11, кв. 323",
          "field": 4
        },
        {
          "value": "Сидоровым Данилой Петровичем",
          "field": 5
        },
        {
          "value": "№3",
          "field": 6
        },
        {
          "value": "1.11.2023",
          "field": 7
        },
        {
          "value": "20.11.2023",
          "field": 8
        },
        {
          "value": "30.10.2023",
          "field": 9
        }
    ]
}

### Добавить новый шаблон и описание его полей в базу (ТОЛЬКО ДЛЯ АДМИНА)
POST {{URL}}/templates/
Content-Type: application/json
Authorization: {{TOKEN}}

{
    "name": "Заявление в детский сад",
    "deleted": true,
    "description": "Данный шаблон необходим для заполнения заявления в детский сад. Заявление может быть составлено в простой письменной форме. Можно доработать шаблон под себя и прописать наиболее важные поля после его скачивания.",
    "fields": [
        {
            "tag": "ДетскийСадНомерНазвание",
            "name": "Номер и название детского сада",
            "hint": "66 Непоседы",
            "group": 1,
            "type": "str20",
            "length": 40
        },
        {
            "tag": "АдресатФИО",
            "name": "ФИО заведующего (укажите в дательном падеже)",
            "hint": "Ивановой Ирине Петровне",
            "group": 2,
            "type": "fio",
            "length": 40
            
        },
        {
            "tag": "ОтправительФИО",
            "name": "ФИО родителя/законного представителя (в родительном падеже)",
            "hint": "Иванова Ивана Ивановича",
            "group": 3,
            "type": "fio",
            "length": 40
        },
        {
            "tag": "ОтправительПочтовыйАдрес",
            "name": "Почтовый адрес",
            "hint": "город, улица, номер квартиры",
            "group": 3,
            "type": "str40",
            "length": 40
        },
        {
            "tag": "РебенокФИО",
            "name": "ФИО ребенка (в творительном падеже)",
            "hint": "Ивановым Данилой Ивановичем",
            "group": 4,
            "type": "fio",
            "length": 40
        },
        {
            "tag": "РебенокГруппа",
            "name": "Номер или название группы",
            "hint": "№3 или средняя",
            "group": 4,
            "type": "str20",
            "length": 40
        },
        {
            "tag": "Дата1",
            "name": "Дата начала отпуска",
            "hint": "дд.мм.гггг",
            "type": "date",
            "length": 40
        },
        {
            "tag": "Дата2",
            "name": "Дата окончания отпуска",
            "hint": "дд.мм.гггг",
            "type": "date",
            "length": 40
        },
        {
            "tag": "Дата3",
            "name": "Дата подачи заявления",
            "hint": "дд.мм.гггг",
            "type": "date",
            "length": 40
        }
    ],
    "groups": [
        {
            "id": 1,
            "name": "Данные о детском саде"
        },
        {
            "id": 2,
            "name": "Адресат"
        },
        {
            "id": 3,
            "name": "Отправитель"
        },
        {
            "id": 4,
            "name": "Ребенок"
        }
    ]
}

