@TOKEN = Token b5b767cb36da725f900892f627a28dc1c0e40488
# @URL = https://documents-template.site/
@URL = http://127.0.0.1:8000

###
POST {{URL}}/api/users/
Content-Type: application/json

{
    "email": "nikox12@mail.ru",
    "username": "nikox122@mail.ru",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

###
POST {{URL}}/api/auth/token/login/
Content-Type: application/json

{
    "email": "nik3ox1e21@mail.ru",
    "password": "456852Zx"
}

###
POST {{URL}}/api/users/set_password/
Content-Type: application/json
Authorization: {{TOKEN}}

{
"new_password": "456852Zxы",
"current_password": "456852Zx1ы"
}

###
GET {{URL}}/api/users/me/ 
Content-Type: application/json
Authorization: {{TOKEN}}

{
}


###
GET {{URL}}/api/users/2/ 
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

