@TOKEN = Token c911144116cd1689f8fd01e00102bcd1ce4cc175
@URL = https://doki.pro/api/v2
# @URL = http://127.0.0.1:8000/api/v2

###
POST {{URL}}/users/
Content-Type: application/json

{
    "email": "nikox1181182@mail.ru",
    "username": "nikox1122@mail.ru",
    "password": "456852Zx",
    "first_name": "kewk",
    "last_name": "wsq"
}

###
POST {{URL}}/auth/token/login/
Content-Type: application/json

{
    "email": "nikox1181182@mail.ru",
    "password": "456852Zx"
}

###
POST {{URL}}/users/set_password/
Content-Type: application/json
Authorization: {{TOKEN}}

{
"new_password": "456852Zxы",
"current_password": "456852Zx1ы"
}

###
GET {{URL}}/users/me/ 
Content-Type: application/json
Authorization: {{TOKEN}}

{
}


###
GET {{URL}}/users/2/ 
Content-Type: application/json
Authorization: {{TOKEN}}

{
}

