# Generated by Django 3.2 on 2024-01-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('completed', models.BooleanField(default=False, verbose_name='Документ заполнен')),
                ('description', models.TextField(verbose_name='Описание документа')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('created',),
                'default_related_name': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='templates/', verbose_name='Файл шаблона')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование шаблона')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(verbose_name='Удален')),
                ('description', models.TextField(verbose_name='Описание шаблона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Картинка')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='documents.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ('name',),
                'default_related_name': 'templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SlugField(unique=True, verbose_name='Тип данных')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование типа')),
                ('mask', models.CharField(blank=True, max_length=255, verbose_name='Маска допустимых значений')),
            ],
            options={
                'verbose_name': 'Тип поля шаблона',
                'verbose_name_plural': 'Типы поля шаблона',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование группы полей')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='documents.template', verbose_name='Шаблон')),
                ('type_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_objects.baseobject', verbose_name='Обьект')),
            ],
            options={
                'verbose_name': 'Группа полей',
                'verbose_name_plural': 'Группы полей',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Тэг поля')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование поля')),
                ('hint', models.CharField(blank=True, max_length=255, verbose_name='Подсказка')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер поля ввода')),
                ('default', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение по умолчанию')),
                ('base_object_field', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='base_objects.baseobjectfield', verbose_name='Поле базового обьекта')),
                ('group', models.ForeignKey(blank=True, help_text='Группа полей в шаблоне', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='documents.templatefieldgroup', verbose_name='Группа')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.template', verbose_name='Шаблон')),
                ('type', models.ForeignKey(blank=True, help_text='Тип поля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='documents.templatefieldtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Поле шаблона',
                'verbose_name_plural': 'Поля шаблона',
                'ordering': ('template', 'name'),
                'default_related_name': 'fields',
            },
        ),
        migrations.CreateModel(
            name='FavTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_templates', to='documents.template', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный шаблон',
                'verbose_name_plural': 'Избранные шаблоны',
                'ordering': ('user', 'template'),
                'default_related_name': 'favorite_templates',
            },
        ),
        migrations.CreateModel(
            name='FavDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_documents', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный документ',
                'verbose_name_plural': 'Избранные документы',
                'ordering': ('user', 'document'),
                'default_related_name': 'favorite_documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Содержимое поля')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_fields', to='documents.document', verbose_name='Документ')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_fields', to='documents.templatefield', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Поле документа',
                'verbose_name_plural': 'Поля документа',
                'ordering': ('field__template', 'field'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.template', verbose_name='Шаблон'),
        ),
        migrations.AddConstraint(
            model_name='favtemplate',
            constraint=models.UniqueConstraint(fields=('user', 'template'), name='unique_user_template'),
        ),
        migrations.AddConstraint(
            model_name='favdocument',
            constraint=models.UniqueConstraint(fields=('user', 'document'), name='unique_user_document'),
        ),
    ]
