# Generated by Django 3.2 on 2023-10-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('created',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documentfield',
            options={'verbose_name': 'Поле документа', 'verbose_name_plural': 'Поля документа'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('name',), 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterModelOptions(
            name='templatefield',
            options={'ordering': ('name',), 'verbose_name': 'Поле шаблона', 'verbose_name_plural': 'Поля шаблона'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='document',
            name='completed',
            field=models.BooleanField(verbose_name='Статус документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(verbose_name='Описание документа'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='description',
            field=models.TextField(verbose_name='Описание поля'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Содержимое поля'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(verbose_name='Описание шаблона'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование шаблона'),
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='hint',
            field=models.TextField(verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование поля'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='tag',
            field=models.CharField(max_length=255, verbose_name='Тэг поля'),
        ),
    ]
