# Generated by Django 3.2 on 2023-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20231007_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='hint',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка'),
        ),
    ]
