# Generated by Django 3.2 on 2023-10-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.template', verbose_name='Шаблон'),
        ),
    ]
