# Generated by Django 3.2 on 2023-10-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20231011_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fields',
            field=models.ManyToManyField(through='documents.FieldToDocument', to='documents.DocumentField'),
        ),
    ]
