# Generated by Django 3.2 on 2023-10-11 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_alter_templatefield_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='template',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Дата модификации'),
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона'),
        ),
    ]
