# Generated by Django 3.2 on 2023-10-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='fields',
            new_name='docuemnt_fields',
        ),
    ]
