# Generated by Django 3.2 on 2023-10-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_rename_fields_document_docuemnt_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docuemnt_fields',
            new_name='document_fields',
        ),
    ]
