# Generated by Django 3.2 on 2023-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_rename_docuemnt_fields_document_document_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='template_id',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='documentfield',
            old_name='field_id',
            new_name='field',
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='description',
            field=models.TextField(default='Нет описания', verbose_name='Описание поля'),
        ),
    ]
