# Generated by Django 3.2 on 2023-10-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20231011_2320'),
        ('documents', '0010_auto_20231014_1451'),
    ]

    operations = [
    ]
