# Generated by Django 3.2 on 2023-10-14 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0011_merge_0007_auto_20231011_2320_0010_auto_20231014_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='description',
            field=models.TextField(verbose_name='Описание поля'),
        ),
        migrations.CreateModel(
            name='FavTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.template', verbose_name='Шаблон')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный шаблон',
                'verbose_name_plural': 'Избранные шаблоны',
            },
        ),
        migrations.CreateModel(
            name='FavDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный документ',
                'verbose_name_plural': 'Избранные документы',
            },
        ),
    ]
