# Generated by Django 3.2 on 2023-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20231014_2225'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favdocument',
            constraint=models.UniqueConstraint(fields=('user', 'document'), name='unique_user_document'),
        ),
        migrations.AddConstraint(
            model_name='favtemplate',
            constraint=models.UniqueConstraint(fields=('user', 'template'), name='unique_user_template'),
        ),
    ]
