# Generated by Django 3.2 on 2023-10-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20231014_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.template', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.templatefield', verbose_name='Поле'),
        ),
    ]
