# Generated by Django 3.2 on 2023-10-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0016_auto_20231018_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'default_related_name': 'documents', 'ordering': ('created',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_fields',
            field=models.ManyToManyField(related_name='documents', through='documents.FieldToDocument', to='documents.DocumentField'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.template', verbose_name='Шаблон'),
        ),
    ]
