# Generated by Django 3.2 on 2023-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20231019_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание поля'),
        ),
    ]
