# Generated by Django 3.2 on 2023-10-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_documentfield_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Тип данных')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование типа')),
                ('mask', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маска допустимых значений')),
            ],
            options={
                'verbose_name': 'Тип поля шаблона',
                'verbose_name_plural': 'Типы поля шаблона',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='templatefield',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Тип поля', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.templatefieldtype', verbose_name='Тип'),
        ),
    ]
