# Generated by Django 3.2 on 2023-10-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_alter_templatefield_hint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatefieldtype',
            old_name='slug',
            new_name='type',
        ),
    ]
