# Generated by Django 3.2 on 2023-10-25 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0021_rename_slug_templatefieldtype_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfield',
            options={'ordering': ('field__template', 'field'), 'verbose_name': 'Поле документа', 'verbose_name_plural': 'Поля документа'},
        ),
        migrations.AlterModelOptions(
            name='favdocument',
            options={'default_related_name': 'favorite_documents', 'ordering': ('user', 'document'), 'verbose_name': 'Избранный документ', 'verbose_name_plural': 'Избранные документы'},
        ),
        migrations.AlterModelOptions(
            name='favtemplate',
            options={'default_related_name': 'favorite_templates', 'ordering': ('user', 'template'), 'verbose_name': 'Избранный шаблон', 'verbose_name_plural': 'Избранные шаблоны'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'default_related_name': 'templates', 'ordering': ('name',), 'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterModelOptions(
            name='templatefield',
            options={'default_related_name': 'fields', 'ordering': ('template', 'name'), 'verbose_name': 'Поле шаблона', 'verbose_name_plural': 'Поля шаблона'},
        ),
        migrations.AlterField(
            model_name='document',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Документ заполнен'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание поля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_fields', to='documents.templatefield', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='favdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_documents', to='documents.document', verbose_name='Документ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_documents', to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favtemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_templates', to='documents.template', verbose_name='Шаблон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favtemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_templates', to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldtodocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_of_field', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='fieldtodocument',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_document', to='documents.documentfield'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='documents.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подсказка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Тип поля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='documents.templatefieldtype', verbose_name='Тип'),
        ),
    ]
