# Generated by Django 3.2 on 2023-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_templatefield_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
