# Generated by Django 3.2 on 2023-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_templatefield_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefield',
            name='image',
        ),
        migrations.AddField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
