# Generated by Django 3.2 on 2023-11-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_auto_20231107_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_fields',
        ),
        migrations.AddField(
            model_name='documentfield',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_fields', to='documents.document', verbose_name='Документ'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FieldToDocument',
        ),
    ]
