# Generated by Django 3.2 on 2023-11-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_auto_20231108_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfield',
            name='description',
        ),
    ]
