# Generated by Django 3.2 on 2023-11-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_remove_documentfield_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата модификации'),
        ),
    ]
