# Generated by Django 3.2 on 2023-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_alter_template_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='modified',
        ),
        migrations.AddField(
            model_name='template',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
