# Generated by Django 3.2 on 2023-11-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_auto_20231118_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.FileField(upload_to='templates/', verbose_name='Файл шаблона'),
        ),
    ]
