# Generated by Django 3.2 on 2023-11-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_alter_template_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='default',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение по умолчанию'),
        ),
    ]
