# Generated by Django 3.2 on 2024-01-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0004_auto_20240102_2047'),
        ('documents', '0032_templatefield_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefieldgroup',
            name='type_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_objects.baseobject', verbose_name='Обьект'),
        ),
    ]
