# Generated by Django 3.2 on 2024-01-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_objects', '0005_alter_object_base_object'),
        ('documents', '0033_templatefieldgroup_type_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='base_object_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='base_objects.baseobjectfield', verbose_name='Поле базового обьекта'),
        ),
    ]
