# Generated by Django 3.2 on 2023-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Данная почта уже используется'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
